### ISSUE TITLE
Explicit license for the data?

### ISSUE THREAD

**Issue by kzawisto** [IMNearth/CoAT#11]
Hello 
Thanks for sharing your great work.

Could you please add explicit license information about the code and dataset? Is Apache 2.0 License applied to dataset?

I am interested in using your dataset for research, but I need a license to comply with the regulations.

Thanks.

**Comment by IMNearth** [comment]
Hi kzawisto, 

Yes, the dataset is under license Apache 2.0. 

Here is the license file. 
[LICENSE.txt](https://github.com/user-attachments/files/17536166/LICENSE.txt)
