### ISSUE TITLE
[Bug Report] Requirement for resolving bugs of mismatched information in the released data and MIME type

### ISSUE THREAD

**Issue by Li-Qingyun** [IMNearth/CoAT#14]
## 1. It seems that there are many mismatched information in the released data.

The code raised a bug [here[161 line]](https://github.com/IMNearth/CoAT/blob/9ab1a9f0e76581c50c84f8ebc6ada1a2084a0c71/coat/agent.py#L161)

https://github.com/IMNearth/CoAT/blob/9ab1a9f0e76581c50c84f8ebc6ada1a2084a0c71/coat/agent.py#L158-L161

because the step_data['next_image_full_path'] is None.

I found several episode whose latest action type are not 10/11. And I provide the following checking code for the released data.

The last steps are not finished steps for the two episode.
8208572071774959988
5460768153873175219

```python
def check_data(cfg):
    aitz = AITZDataset(cfg.DATA.SPLIT, cfg.DATA.DATA_DIR, ratio=1, double_sample=False)
    episode_data = aitz.episode_data

    def check_step_id(episode_steps):
        for idx, episode_step in enumerate(episode_steps):
            episode_id = episode_step["step_id"]
            if idx != episode_id:
                return True
        return False
    
    print("Step ids mismatch")
    for episode_steps in episode_data:
        if check_step_id(episode_steps):
            print(episode_steps[-1]["episode_id"], episode_steps[-1]["image_path"])
    print("\n\n")
    print("There are lacked steps")
    for episode_steps in episode_data:
        last_episode_step = episode_steps[-1]
        last_result_action_type = episode_steps[-1]["result_action_type"]
        episode_length = episode_steps[-1]["episode_length"]
        if len(episode_steps) != episode_length:
            # print(last_episode_step)
            print(last_episode_step["episode_id"], last_episode_step["image_path"])
    print("\n\n")
    print("The last steps are not finished steps")
    for episode_steps in episode_data:
        last_episode_step = episode_steps[-1]
        last_result_action_type = episode_steps[-1]["result_action_type"]
        episode_length = episode_steps[-1]["episode_length"]
        if last_result_action_type not in [10, 11]:
            # print(last_episode_step)
            print(last_episode_step["episode_id"], last_episode_step["image_path"])
```

## 2. It seems that MIME type of image base64 string is wrong.

https://github.com/IMNearth/CoAT/blob/9ab1a9f0e76581c50c84f8ebc6ada1a2084a0c71/coat/model.py#L82

jepg -> jpeg

But it seems that the image parsers of openai are lenient in parsing MIME types. Although "jepg" is an invalid MIME type, when the parser encounters data:image/jepg, it attempts to decode the image based on the actual content of the data rather than strictly validating the MIME type.

**Comment by IMNearth** [comment]
Dear Qingyun, 

In our paper we have noted that there are many redundant steps in original AITW dataset. So we corrected it by manually removing some duplicated or useless steps. The resuting episodes in AITZ dataset contains the same or less steps, therefore the key "episode_length", which is from the original AITW dataset, should be ignored.

In our previous implementation, the MIME type "jepg" or "jpeg" did not influence the result. But thank you for pointing this our. We will correct it later.

Jiwen

**Comment by Li-Qingyun** [comment]
@IMNearth Hi, thanks for your reply. 

What about the episodes whose latest action type are not 10/11?
8208572071774959988
5460768153873175219

They'll raise the error in flow()
[here[161 line]](https://github.com/IMNearth/CoAT/blob/9ab1a9f0e76581c50c84f8ebc6ada1a2084a0c71/coat/agent.py#L161)

https://github.com/IMNearth/CoAT/blob/9ab1a9f0e76581c50c84f8ebc6ada1a2084a0c71/coat/agent.py#L158-L161
