### ISSUE TITLE
Downloading dataset from Google drive

### ISSUE THREAD

**Issue by HahmDY** [IMNearth/CoAT#5]
Can you open access of Google drive for downloading dataset? It's hard to download dataset from BaiduNetdisk

**Comment by boyugou** [comment]
same question

**Comment by IMNearth** [comment]
Can you download form this [link](https://drive.google.com/file/d/12xOV2m62fBUFLhMcWIsFiC6zwV7a2RhI/view)? This is the google drive download url and is available in the README.

**Comment by HahmDY** [comment]
Without access, I can't download from google drive link.

**Comment by boyugou** [comment]
> Can you download form this [link](https://drive.google.com/file/d/12xOV2m62fBUFLhMcWIsFiC6zwV7a2RhI/view)? This is the google drive download url and is available in the README.

No worries. I've downloaded from BaiduNetdisk. Thanks for sharing.

I requested the permission of the google driver link long time ago but didn't get any response.

**Comment by kzawistowsk** [comment]
Hello. Could you pls give me access to google drive download?

People from EU can't register for Baidu Net Disk.

**Comment by IMNearth** [comment]
Sorry about that. I recently noticed that I did not turn-on "anyone could access this resource via url" option. Here is the new [link](https://drive.google.com/file/d/12xOV2m62fBUFLhMcWIsFiC6zwV7a2RhI/view?usp=sharing). Moreover, I have passed all permission requets of the google drive. Now I guess anybody could have access to AiTZ dataset.
