### ISSUE TITLE
please explain hit and acc on this paper.

### ISSUE THREAD

**Issue by yanlinchn** [IMNearth/CoAT#7]
Could you help describe more details on ""hit" means format hit rate, and "acc" means accuracy. I am confused with these two metrics.

**Comment by IMNearth** [comment]
Format hit rate means that, when we want the model to output the desired action format, i.e. "click(bbox=[x1, y1, x2, y2])", we have to parse the response string from the model. If we can not parse the desired information, we label the model "fail to hit the format".
