### ISSUE TITLE
Execution error when running run_coat.py

### ISSUE THREAD

**Issue by GasolSun36** [IMNearth/CoAT#9]
Hi, thanks for your excellent work! However, when I was running the example code:

`python run_coat.py --task "flow" --DEMO_MODE "COAT" --MODEL.NAME "openai/gemini/qwenvl" --num-threads 3
`
I get 

> usage: run_coat.py [-h] [--config-file FILE] [--task {try,flow,predict,eval}] [--num-threads NUM_THREADS] [--seed SEED] ...
run_coat.py: error: unrecognized arguments: --DEMO_MODE

It seems there is no argument DEMO_MODE or MODEL.NAME in the main file.

When I just simply run:

`
python run_coat.py --task "flow" --num-threads 3
`

I get NotImplementedError.

Can you explain this? thanks!

**Comment by Li-Qingyun** [comment]
use `python run_coat.py --task "flow" --num-threads 1  DEMO_MODE "COAT" MODEL.NAME "gemini"`
